default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: offside_development

test:
  <<: *default
  database: offside_test


production:
  <<: *default
  database: offside_production
  username: offside24
  password: <%= ENV['OFFSIDE_DATABASE_PASSWORD'] %>
